// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzpbOVVbVMPetJkEWAO3CCboE2Qz8lPMY',
    appId: '1:20799717000:web:097b3294ad2cc95f11693d',
    messagingSenderId: '20799717000',
    projectId: 'schoolmanagement-7640b',
    authDomain: 'schoolmanagement-7640b.firebaseapp.com',
    databaseURL: 'https://schoolmanagement-7640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolmanagement-7640b.firebasestorage.app',
    measurementId: 'G-LV5FG5ME3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIa90kf1DNeCx-Rozctc0yGvumL-cUfA',
    appId: '1:20799717000:android:28f25647ec57a87d11693d',
    messagingSenderId: '20799717000',
    projectId: 'schoolmanagement-7640b',
    databaseURL: 'https://schoolmanagement-7640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolmanagement-7640b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ovajz-nhGn-z8khCK7tvRaWjUpLF16c',
    appId: '1:20799717000:ios:a5f3427d8ec0333f11693d',
    messagingSenderId: '20799717000',
    projectId: 'schoolmanagement-7640b',
    databaseURL: 'https://schoolmanagement-7640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolmanagement-7640b.firebasestorage.app',
    iosBundleId: 'com.tb.jogs.co',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ovajz-nhGn-z8khCK7tvRaWjUpLF16c',
    appId: '1:20799717000:ios:a5f3427d8ec0333f11693d',
    messagingSenderId: '20799717000',
    projectId: 'schoolmanagement-7640b',
    databaseURL: 'https://schoolmanagement-7640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolmanagement-7640b.firebasestorage.app',
    iosBundleId: 'com.tb.jogs.co',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzpbOVVbVMPetJkEWAO3CCboE2Qz8lPMY',
    appId: '1:20799717000:web:b99ef740171d0d5811693d',
    messagingSenderId: '20799717000',
    projectId: 'schoolmanagement-7640b',
    authDomain: 'schoolmanagement-7640b.firebaseapp.com',
    databaseURL: 'https://schoolmanagement-7640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'schoolmanagement-7640b.firebasestorage.app',
    measurementId: 'G-25ZH9B4QQ8',
  );
}
